// <auto-generated>
// Rewired Constants
// This list was generated on 11/6/2018 10:22:01 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal Movement in UI")]
        public const int UIHORIZONTAL = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical Movement in UI")]
        public const int UIVERTICAL = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UISubmit")]
        public const int UISUBMIT = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "UICancel")]
        public const int UICANCEL = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MOVE_HORIZONTAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MOVE_VERTICAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int AIMHORIZONTAL = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "AimVertical")]
        public const int AIMVERTICAL = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "PickUpWeapon")]
        public const int PICKUPWEAPON = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "ThrowWeapon")]
        public const int THROWWEAPON = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Shoot")]
        public const int SHOOT = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Joins in playerselection")]
        public const int JOINLOBBY = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Leave Lobby")]
        public const int LEAVELOBBY = 40;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Return Lobby")]
        public const int RETURNLOBBY = 41;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Confirm Player Selection")]
        public const int CONFIRMPLAYERSELECTION = 42;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Changes Color in Playerselection")]
        public const int CHANGECOLORRIGHT = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Changes Color in Playerselection")]
        public const int CHANGECOLORLEFT = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Pauses the Game")]
        public const int PAUSE_GAME = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Unpauses the Game")]
        public const int UNPAUSE_GAME = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LevelSelectionLeft")]
        public const int LEVELSELECTIONLEFT = 43;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LevelSelectionRight")]
        public const int LEVELSELECTIONRIGHT = 44;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LevelSelectionSubmit")]
        public const int LEVELSELECTIONSUBMIT = 45;
        // Controller Test
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickLeftHor")]
        public const int STICKLEFTHOR = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickLeftVer")]
        public const int STICKLEFTVER = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickRightHor")]
        public const int STICKRIGHTHOR = 22;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickRightVer")]
        public const int STICKRIGHTVER = 23;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "TriggerRight")]
        public const int TRIGGERRIGHT = 24;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "TriggerLeft")]
        public const int TRIGGERLEFT = 25;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "DPadUp")]
        public const int DPADUP = 26;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "DPadLeft")]
        public const int DPADLEFT = 29;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "DPadRight")]
        public const int DPADRIGHT = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "DPadDown")]
        public const int DPADDOWN = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "FaceButonTop")]
        public const int FACEBUTTONTOP = 30;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "FaceButonLeft")]
        public const int FACEBUTTONLEFT = 33;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "FaceButonRight")]
        public const int FACEBUTTONRIGHT = 32;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "FaceButonBottom")]
        public const int FACEBUTTONBOTTOM = 31;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "Start")]
        public const int START = 34;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "Select")]
        public const int SELECT = 35;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "BumperLeft")]
        public const int BUMPERLEFT = 36;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "BumperRight")]
        public const int BUMPERRIGHT = 37;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickLeftButton")]
        public const int STICKLEFTBUTTON = 38;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Controller Test", friendlyName = "StickRightButton")]
        public const int STICKRIGHTBUTTON = 39;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
        public const int MENU_UI_CONTROL = 1;
        public const int PLAYERSELECTION = 2;
        public const int CHARACTERCONTROL = 3;
        public const int PAUSEMENU_CONTROL = 4;
        public const int CONTROLLER_TEST = 5;
        public const int LEVELSELECTION = 6;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int DEFAULT = 0;
        }
        public static partial class Keyboard {
            public const int DEFAULT = 0;
        }
        public static partial class Mouse {
            public const int DEFAULT = 0;
        }
        public static partial class CustomController {
            public const int DEFAULT = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int PLAYER1 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int PLAYER2 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player3")]
        public const int PLAYER3 = 2;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player4")]
        public const int PLAYER4 = 3;
    }
    public static partial class CustomController {
    }
}
